name: SSH Login

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: "0 0 */20 * *"  # 每 20 天运行一次

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Set execute permissions for script
        run: chmod +x ssh-login.sh

      - name: Run SSH Login Script
        run: ./ssh-login.sh
        env:
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
