name: SSH Login

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: "0 0 */20 * *"  # 每 20 天运行一次

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Process SSH Login
        run: |
          # 读取 Secrets，使用逗号作为分隔符
          IFS=',' read -r -a servers <<< "${{ secrets.SSH_SERVER }}"
          IFS=',' read -r -a users <<< "${{ secrets.SSH_USER }}"
          IFS=',' read -r -a passwords <<< "${{ secrets.SSH_PASS }}"

          # 确保数组长度一致
          if [[ ${#servers[@]} -ne ${#users[@]} || ${#servers[@]} -ne ${#passwords[@]} ]]; then
            echo "Error: SSH_SERVER, SSH_USER, SSH_PASS 行数不匹配!"
            exit 1
          fi

          # 遍历服务器、用户和密码
          for i in "${!servers[@]}"; do
            SERVER="${servers[$i]}"
            USER="${users[$i]}"
            PASS="${passwords[$i]}"

            echo "Logging in as $USER on $SERVER..."

            sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -tt "$USER@$SERVER" << EOF
                echo "登录成功 - 用户: $USER"
                ls -lah
                exit
EOF
          done
